# behavior: domain
payload:
  - +.turborepo.com
  - +.docs.siliconflow.cn
  - +.turbo.build
  - +.rolldown.rs
  - +.prisma.io
  - +.prisma-data.net
  - +.elysiajs.com
  - +.rollupjs.org
  - +.aihubmix.com
